services:
    fsc.common.rest.controller.root:
        class: FSC\Common\RestBundle\Controller\RootController
        arguments:
          - []
          - @fos_rest.view_handler
          - @fsc.common.rest.factory.atom_link
          - @router

    fsc.common.rest.resource.controller:
        abstract: true
        class: FSC\Common\RestBundle\Controller\ResourceController
        arguments:
          - null # The resource
          - @fos_rest.view_handler
          - @jms_serializer.xml_serialization_visitor
