services:
    fsc.rest.collection.form:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
          - search
          - fsc_rest_collection

    fsc.rest.collection_search.form:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
          - search
          - fsc_rest_collection_search
