services:
    fsc.rest.normalizer.form:
        class: FSC\RestBundle\Normalizer\FormNormalizer
        arguments:
          - @fsc.rest.factory.atom_link

    fsc.rest.normalizer.pagerfanta:
        class: FSC\RestBundle\Normalizer\PagerfantaNormalizer
        arguments:
          - FSC\RestBundle\Model\Representation\Collection
