parameters:
    fsc.common.rest.factory.atom_link.rel_prefix: ''

services:
    fsc.common.rest.factory.atom_link:
        class: FSC\Common\RestBundle\REST\AtomLinkFactory
        arguments:
          - %fsc.common.rest.factory.atom_link.rel_prefix%

    fsc.common.rest.resource.abstract:
        abstract: true
        class: FSC\Common\RestBundle\REST\AbstractResource
        calls:
          - [ setRouter, [ @router ] ]
          - [ setFormNormalizer, [ @fsc.common.rest.normalizer.form ] ]
          - [ setFormFactory, [ @form.factory ] ]
          - [ setAtomLinkFactory, [ @fsc.common.rest.factory.atom_link ] ]
          - [ setSecurityContext, [ @security.context ] ]
          - [ setContainer, [ @service_container ] ]

    fsc.common.rest.resource.abstract_doctrine:
        abstract: true
        parent: fsc.common.rest.resource.abstract
        calls:
          - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]
